trigger:
- main

pr:
- main

pool: agentpool-001

variables:
  coalesceCliVersion: '6.2.21'

jobs:
- job: deploy
  displayName: 'Deploy to Environment'
  steps:
  - checkout: self
  
  - task: DownloadSecureFile@1
    name: coaConfig
    displayName: 'Download coa config'
    inputs:
      secureFile: 'config'
      retryCount: '3'

  - script: |
      echo "$(coaConfig)" > coaConfig
    env:
      coaConfig: $(secrets.coaConfig)

  - script: |
      npm i -g pnpm
      npm list -g | grep "@coalescesoftware/coa@$(coalesceCliVersion)" || npm install -g @coalescesoftware/coa@$(coalesceCliVersion);
    displayName: 'Install Coalesce CLI'

  - script: 'npx coa --version'
    displayName: 'Print Coa Version'

  - script: |
      npx coa plan --config coaConfig --out ./coa-plan --debug
    displayName: 'Create Deployment Plan'

  - script: |
      npx coa deploy --config coaConfig --plan ./coa-plan --debug
    displayName: 'Deploy Plan'
