pool: agentpool-001

variables:
 - name: coalesceCliVersion
   value: latest 

trigger:
  branches:
    include:
    - main

steps:

- task: DownloadSecureFile@1
  name: coaConfig
  displayName: 'Download coa config'
  inputs:
    secureFile: 'config'

- task: CmdLine@2
  inputs:
    script: |
      # Install Coalesce CLI tool, if not installed
      npm list -g | grep "@coalescesoftware/coa@$(coalesceCliVersion)" || npm install -g @coalescesoftware/coa@$(coalesceCliVersion);
      
      # Start refresh
      coa plan  --config $(coaConfig.secureFilePath);
      coa deploy  --config $(coaConfig.secureFilePath);